#!/usr/bin/env python3
"""Run LLM debug queries from human-readable JSON or YAML logs.

Loads LLM interactions saved by LLM JSON logging, reconstructs the request
messages, and re-runs the query with modifications. Useful for iterating on
system prompts, debugging responses, and testing changes without triggering
the full bot.

Usage:
    ./venv/bin/python3 scripts/run_llm_debug_query.py <readable.json>
    ./venv/bin/python3 scripts/run_llm_debug_query.py <readable.yaml>
    ./venv/bin/python3 scripts/run_llm_debug_query.py <readable.json> --model gpt-4

Exit codes:
    0  Query executed successfully
    1  Error loading file, model not found, or API error
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

import yaml

# ---------------------------------------------------------------------------
# Ensure the repository root is on sys.path so that project packages
# (internal/, lib/) are importable when the script is run as:
#     ./venv/bin/python3 scripts/run_llm_debug_query.py
# In that invocation Python adds scripts/ to sys.path, not the repo root.
# ---------------------------------------------------------------------------
_REPO_ROOT = str(Path(__file__).parent.parent.resolve())
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

# ---------------------------------------------------------------------------
# Silence noisy libraries before importing project code.
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.WARNING)
logging.getLogger("httpx").setLevel(logging.ERROR)
logging.getLogger("openai").setLevel(logging.ERROR)
logging.getLogger("openai._base_client").setLevel(logging.ERROR)

from internal.config.manager import ConfigManager  # noqa: E402
from lib.ai import AbstractModel, LLMManager, ModelMessage, ModelResultStatus  # noqa: E402

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# ANSI colour helpers (used only when stdout is a TTY)
# ---------------------------------------------------------------------------
_ANSI_YELLOW = "\033[33m"
_ANSI_GREEN = "\033[32m"
_ANSI_RED = "\033[31m"
_ANSI_BLUE = "\033[34m"
_ANSI_RESET = "\033[0m"

_USE_COLOR: bool = sys.stdout.isatty()


def _col(text: str, code: str) -> str:
    """Wrap *text* in ANSI *code* when colour output is enabled.

    Args:
        text: The string to colourise.
        code: An ANSI escape sequence (e.g. ``_ANSI_YELLOW``).

    Returns:
        Colourised string when stdout is a TTY, plain *text* otherwise.
    """
    if _USE_COLOR:
        return f"{code}{text}{_ANSI_RESET}"
    return text


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------


def buildParser() -> argparse.ArgumentParser:
    """Construct and return the argument parser for this script.

    Returns:
        Configured ``argparse.ArgumentParser`` instance.
    """
    parser = argparse.ArgumentParser(
        prog="run_llm_debug_query.py",
        description=(
            "Load LLM query from human-readable JSON/YAML log and re-run it. "
            "Use this to iterate on prompts, debug responses, or test changes "
            "without triggering the full bot."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  # Run the query as-is using the original model (JSON input)\n"
            "  ./venv/bin/python3 scripts/run_llm_debug_query.py log.readable.json\n\n"
            "  # Run the query as-is using the original model (YAML input)\n"
            "  ./venv/bin/python3 scripts/run_llm_debug_query.py log.readable.yaml\n\n"
            "  # Override the model to use a different one\n"
            "  ./venv/bin/python3 scripts/run_llm_debug_query.py log.readable.json --model gpt-4\n\n"
        ),
    )
    parser.add_argument(
        "inputFile",
        help="Path to human-readable JSON or YAML file (generated by convert_llm_log_to_readable.py)",
    )
    parser.add_argument(
        "--model",
        metavar="NAME",
        default=None,
        help=(
            "Override the model to use. "
            "If not specified, uses the model from the log file. "
            "Example: gpt-4, openrouter/claude-haiku-4.5"
        ),
    )
    parser.add_argument(
        "--config-dir",
        action="append",
        dest="configDirs",
        metavar="DIR",
        help=(
            "Directory to load .toml config files from (can be specified multiple times). "
            "Default: --config-dir configs/00-defaults --config-dir configs/local"
        ),
    )
    parser.add_argument(
        "--dotenv-file",
        default=".env",
        help="Path to .env file with env variables for substitute in configs",
    )
    return parser


def _parseArgs() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        Populated ``argparse.Namespace``.
    """
    return buildParser().parse_args()


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def loadReadableFile(filePath: str) -> List[Dict[str, Any]]:
    """Load and parse a human-readable JSON or YAML file.

    The file can contain either a single JSON/YAML object (one log entry) or
    a JSON/YAML array (multiple entries). Always returns a list for consistency.
    YAML files support multiline strings with literal block style.

    Args:
        filePath: Path to the human-readable JSON or YAML file.

    Returns:
        List of log entry dictionaries. Each entry contains fields like
        'model', 'request', 'response', 'status', etc.

    Raises:
        FileNotFoundError: If the file doesn't exist.
        json.JSONDecodeError: If the file contains invalid JSON (for .json files).
        yaml.YAMLError: If the file contains invalid YAML (for .yaml/.yml files).
        ValueError: If the file extension is not supported.
    """
    path = Path(filePath)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {filePath}")

    # Determine format from file extension
    suffix = path.suffix.lower()

    if suffix in (".yaml", ".yml"):
        # Load as YAML
        return _loadYamlFile(path)
    elif suffix == ".json":
        # Load as JSON
        return _loadJsonFile(path)
    else:
        raise ValueError(f"Unsupported file format: {suffix}. " "Supported formats: .json, .yaml, .yml")


def _loadYamlFile(path: Path) -> List[Dict[str, Any]]:
    """Load a YAML file containing log entries.

    Args:
        path: Path to the YAML file.

    Returns:
        List of log entry dictionaries.

    Raises:
        yaml.YAMLError: If the file contains invalid YAML.
    """
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Load YAML (handles single document or multiple documents)
    try:
        data = yaml.safe_load(content)
    except yaml.YAMLError as e:
        raise yaml.YAMLError(f"Failed to parse YAML from {path}: {e}")

    # Normalize to list: handle both single object and array
    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        return [data]
    else:
        raise ValueError(f"Expected YAML object or array, got {type(data).__name__}")


def _loadJsonFile(path: Path) -> List[Dict[str, Any]]:
    """Load a JSON file containing log entries.

    Args:
        path: Path to the JSON file.

    Returns:
        List of log entry dictionaries.

    Raises:
        json.JSONDecodeError: If the file contains invalid JSON.
    """
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Handle comment lines (lines starting with #)
    filteredContent = "\n".join(line for line in content.split("\n") if not line.strip().startswith("#"))

    try:
        data = json.loads(filteredContent)
    except json.JSONDecodeError as e:
        raise json.JSONDecodeError(
            f"Failed to parse JSON from {path}: {e.msg}",
            e.doc,
            e.pos,
        )

    # Normalize to list: handle both single object and array
    if isinstance(data, list):
        return data
    elif isinstance(data, dict):
        return [data]
    else:
        raise ValueError(f"Expected JSON object or array, got {type(data).__name__}")


# ---------------------------------------------------------------------------
# Main execution
# ---------------------------------------------------------------------------


async def runQueryWithResult(
    model: AbstractModel,
    modelName: str,
    messages: List[ModelMessage],
) -> tuple[ModelResultStatus, str]:
    """Run the LLM query and print results.

    Args:
        model: The AbstractModel instance to query.
        modelName: The name of the model (for display).
        messages: List of ModelMessage objects to send.

    Returns:
        Tuple of (status, resultText).
    """
    from lib.ai.models import ModelRunResult  # noqa: F401

    print(f"Running query with model: {_col(modelName, _ANSI_BLUE)}\n")
    print(f"Message count: {len(messages)}\n")

    # Show first message (usually system prompt) for context
    if messages and messages[0].role == "system":
        systemContent = messages[0].content
        preview = systemContent[:200] + "..." if len(systemContent) > 200 else systemContent
        formattedPreview = _col(preview, _ANSI_GREEN)
        print("System prompt (first 200 chars):\n")
        print(f'  "{formattedPreview}"')

    # Run the query
    startTime = time.time()
    result: ModelRunResult = await model.generateText(messages)
    elapsedTime = time.time() - startTime

    # Store resultText before potentially printing
    resultText = result.resultText or ""

    # Print the result
    print("=" * 80)
    print(_col("RESULT", _ANSI_BLUE))
    print("=" * 80)
    print(
        f"Status: {_col(result.status.name, _ANSI_GREEN if result.status == ModelResultStatus.FINAL else _ANSI_RED)}\n"
    )

    if result.error:
        print(f"Error: {_col(str(result.error), _ANSI_RED)}\n")

    if resultText:
        print("Response:")
        print("-" * 80)
        print(resultText)
        print("-" * 80)
        print()

    print(_col("DETAILS:", _ANSI_YELLOW))
    print(f"  Input tokens:  {result.inputTokens or 'N/A'}")
    print(f"  Output tokens: {result.outputTokens or 'N/A'}")
    print(f"  Total tokens:  {result.totalTokens or 'N/A'}")
    print(f"  Tool calls:    {len(result.toolCalls)}")
    print(f"  Elapsed time:  {elapsedTime:.2f}s")
    if result.toolCalls:
        for tc in result.toolCalls:
            print(f"    - {tc.name}({tc.parameters})")
    print()

    return result.status, resultText


def compareResponses(originalResponse: str, newResponse: str) -> None:
    """Print a side-by-side comparison of original and new responses.

    Args:
        originalResponse: The original response from the log.
        newResponse: The new response from the LLM.
    """
    print("=" * 80)
    print(_col("COMPARISON", _ANSI_BLUE))
    print("=" * 80)

    # Truncate very long responses for display
    maxDisplayLen = 500

    origPreview = originalResponse[:maxDisplayLen] + ("..." if len(originalResponse) > maxDisplayLen else "")
    newPreview = newResponse[:maxDisplayLen] + ("..." if len(newResponse) > maxDisplayLen else "")

    print("\nOriginal response:\n")
    print("-" * 40)
    print(origPreview)
    print("-" * 40)

    print("\nNew response:\n")
    print("-" * 40)
    print(newPreview)
    print("-" * 40)

    # Check if responses are identical
    if originalResponse == newResponse:
        print(f"\n{_col('Responses are identical', _ANSI_GREEN)}")
    else:
        lengthDiff = abs(len(originalResponse) - len(newResponse))
        print(f"\n{_col(f'Responses differ (length diff: {lengthDiff} chars)', _ANSI_YELLOW)}")


async def main() -> int:
    """Main entry point for the script.

    Returns:
        Exit code (0 for success, 1 for error).
    """
    args = _parseArgs()

    # Load the human-readable JSON/YAML file BEFORE initializing ConfigManager
    # because config loading may change the working directory
    print(f"Loading log from: {_col(args.inputFile, _ANSI_BLUE)}")
    try:
        entries = loadReadableFile(args.inputFile)
    except Exception as e:
        print(f"Error loading file: {_col(str(e), _ANSI_RED)}", file=sys.stderr)
        return 1

    if not entries:
        print("No log entries found in file.", file=sys.stderr)
        return 1

    # For simplicity, use the first entry
    entry = entries[0]

    print(f"Found {len(entries)} log entr{'y' if len(entries) == 1 else 'ies'}, using first entry\n")

    # Load config (this may change working directory)
    configDirs: List[str] = args.configDirs if args.configDirs else ["configs/00-defaults", "configs/local"]

    print(f"Loading configs from: {', '.join(configDirs)}")
    configManager = ConfigManager(
        configPath="config.toml",
        configDirs=configDirs,
        dotEnvFile=args.dotenv_file,
    )

    # Initialize LLM manager
    llmManager = LLMManager(configManager.getModelsConfig())

    # Extract metadata
    modelName = args.model or entry.get("model", "")
    if not modelName:
        print("Error: No model specified and no model found in log entry", file=sys.stderr)
        return 1

    print(f"Model: {_col(modelName, _ANSI_BLUE)}")
    if "date" in entry:
        print(f"Original date: {entry['date']}")
    if "status" in entry:
        print(f"Original status: {entry['status']}")
    print()

    # Reconstruct messages
    if "request" not in entry or not isinstance(entry["request"], list):
        print("Error: Log entry missing 'request' field or it is not list of objects", file=sys.stderr)
        return 1

    try:
        messages = ModelMessage.fromDictList(entry["request"])
    except Exception as e:
        print(f"Error reconstructing messages: {_col(str(e), _ANSI_RED)}", file=sys.stderr)
        return 1

    # Get the model
    model = llmManager.getModel(modelName)
    if model is None:
        availableModels = llmManager.listModels()
        print(
            f"Error: Model '{modelName}' not found in configuration.\n",
            file=sys.stderr,
        )
        print(f"Available models: {', '.join(availableModels)}", file=sys.stderr)
        return 1

    # Run the query
    try:
        status, newResponse = await runQueryWithResult(model, modelName, messages)
    except Exception as e:
        print(f"Error running query: {_col(str(e), _ANSI_RED)}", file=sys.stderr)
        logger.exception("Query failed")
        return 1

    # Compare with original response if available
    if "response" in entry and entry["response"]:
        print()
        compareResponses(entry["response"], newResponse)

    return 0 if status == ModelResultStatus.FINAL else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
