"""
Renderers for Gromozeka Markdown Parser

This module provides rendering functionality to convert the parsed
Markdown AST into various output formats including HTML, Markdown, and MarkdownV2.

Classes:
    HTMLRenderer: Converts Markdown AST to HTML5-compliant output
    MarkdownRenderer: Converts AST back to standard Markdown format
    MarkdownV2Renderer: Converts AST to Telegram's MarkdownV2 format with proper escaping

Example:
    >>> from lib.markdown.parser import MarkdownParser
    >>> from lib.markdown.renderer import HTMLRenderer
    >>> parser = MarkdownParser()
    >>> document = parser.parse("# Hello World")
    >>> renderer = HTMLRenderer()
    >>> html = renderer.render(document)
    >>> print(html)
    <h1>Hello World</h1>
"""

import html
from typing import Any, Dict

from .ast_nodes import (
    EmphasisType,
    ListType,
    MDAutolink,
    MDBlockQuote,
    MDCodeBlock,
    MDCodeSpan,
    MDDocument,
    MDEmphasis,
    MDHeader,
    MDHorizontalRule,
    MDImage,
    MDLink,
    MDList,
    MDListItem,
    MDNode,
    MDParagraph,
    MDText,
    Optional,
)


class HTMLRenderer:
    """
    Renderer that converts Markdown AST to HTML5-compliant output.

    This renderer traverses the Abstract Syntax Tree (AST) generated by the Markdown
    parser and generates clean, semantic HTML output following HTML5 standards. It
    supports various rendering options for customization.

    Attributes:
        options: Dictionary of rendering configuration options
        escape_html: Whether to escape HTML special characters in text content
        add_line_breaks: Whether to add line breaks in output
        code_class_prefix: Prefix for code block language classes (default: "language-")
        indent_size: Number of spaces per indentation level (default: 2)
        _indent_level: Current indentation level for pretty printing

    Example:
        >>> renderer = HTMLRenderer({"escape_html": True, "code_class_prefix": "lang-"})
        >>> html = renderer.render(document)
    """

    def __init__(self, options: Optional[Dict[str, Any]] = None) -> None:
        """
        Initialize the HTML renderer with optional configuration.

        Args:
            options: Optional dictionary of rendering configuration options. Supported keys:
                - escape_html (bool): Whether to escape HTML special characters (default: True)
                - add_line_breaks (bool): Whether to add line breaks in output (default: True)
                - code_class_prefix (str): Prefix for code block language classes (default: "language-")
                - indent_size (int): Number of spaces per indentation level (default: 2)
        """
        self.options: Dict[str, Any] = options or {}

        # Default rendering options
        self.escape_html: bool = self.options.get("escape_html", True)
        self.add_line_breaks: bool = self.options.get("add_line_breaks", True)
        self.code_class_prefix: str = self.options.get("code_class_prefix", "language-")
        self.indent_size: int = self.options.get("indent_size", 2)

        # Current indentation level for pretty printing
        self._indent_level: int = 0

    def render(self, document: MDDocument) -> str:
        """
        Render a Markdown document to HTML string.

        This is the main entry point for rendering. It validates the input document
        and renders all child nodes to HTML.

        Args:
            document: The root MDDocument node to render

        Returns:
            HTML string representation of the document

        Raises:
            ValueError: If the provided document is not an instance of MDDocument

        Example:
            >>> parser = MarkdownParser()
            >>> doc = parser.parse("# Hello\\nWorld")
            >>> renderer = HTMLRenderer()
            >>> html = renderer.render(doc)
            >>> print(html)
            <h1>Hello</h1>
            <p>World</p>
        """
        if not isinstance(document, MDDocument):
            raise ValueError("Expected MDDocument as root node")

        html_parts: list[str] = []
        for child in document.children:
            html_parts.append(self._render_node(child))

        return "\n".join(html_parts)

    def _render_node(self, node: MDNode) -> str:
        """
        Render a single AST node to HTML based on its type.

        This method dispatches to the appropriate rendering method based on the
        node's type. It handles all known node types and provides a fallback for
        unknown types.

        Args:
            node: The AST node to render

        Returns:
            HTML string representation of the node

        Note:
            Unknown node types are rendered as HTML comments for debugging purposes.
        """
        if isinstance(node, MDDocument):
            return self._render_document(node)
        elif isinstance(node, MDParagraph):
            return self._render_paragraph(node)
        elif isinstance(node, MDHeader):
            return self._render_header(node)
        elif isinstance(node, MDCodeBlock):
            return self._render_code_block(node)
        elif isinstance(node, MDBlockQuote):
            return self._render_block_quote(node)
        elif isinstance(node, MDList):
            return self._render_list(node)
        elif isinstance(node, MDListItem):
            return self._render_list_item(node)
        elif isinstance(node, MDHorizontalRule):
            return self._render_horizontal_rule(node)
        elif isinstance(node, MDEmphasis):
            return self._render_emphasis(node)
        elif isinstance(node, MDLink):
            return self._render_link(node)
        elif isinstance(node, MDImage):
            return self._render_image(node)
        elif isinstance(node, MDCodeSpan):
            return self._render_code_span(node)
        elif isinstance(node, MDText):
            return self._render_text(node)
        elif isinstance(node, MDAutolink):
            return self._render_autolink(node)
        else:
            # Fallback for unknown node types
            return f"<!-- Unknown node type: {type(node).__name__} -->"

    def _render_document(self, node: MDDocument) -> str:
        """
        Render a document node by rendering all its children.

        Args:
            node: The MDDocument node to render

        Returns:
            Concatenated HTML string of all child nodes
        """
        html_parts: list[str] = []
        for child in node.children:
            html_parts.append(self._render_node(child))
        return "\n".join(html_parts)

    def _render_paragraph(self, node: MDParagraph) -> str:
        """
        Render a paragraph node to HTML.

        Args:
            node: The MDParagraph node to render

        Returns:
            HTML string wrapped in <p> tags, or empty string if content is whitespace
        """
        content = self._render_children(node)
        if not content.strip():
            return ""
        return f"<p>{content}</p>"

    def _render_header(self, node: MDHeader) -> str:
        """
        Render a header node to HTML.

        Args:
            node: The MDHeader node to render

        Returns:
            HTML string wrapped in appropriate <h1>-<h6> tags based on header level
        """
        level = node.level
        content = self._render_children(node)
        return f"<h{level}>{content}</h{level}>"

    def _render_code_block(self, node: MDCodeBlock) -> str:
        """
        Render a code block node to HTML.

        Args:
            node: The MDCodeBlock node to render

        Returns:
            HTML string wrapped in <pre><code> tags with optional language class
        """
        content = self._escape_html(node.content) if self.escape_html else node.content

        if node.language:
            class_attr = f' class="{self.code_class_prefix}{self._escape_html(node.language)}"'
            return f"<pre><code{class_attr}>{content}</code></pre>"
        else:
            return f"<pre><code>{content}</code></pre>"

    def _render_block_quote(self, node: MDBlockQuote) -> str:
        """
        Render a block quote node to HTML.

        Args:
            node: The MDBlockQuote node to render

        Returns:
            HTML string wrapped in <blockquote> tags with nested content
        """
        content: list[str] = []
        for child in node.children:
            content.append(self._render_node(child))

        inner_html = "\n".join(content)
        return f"<blockquote>\n{inner_html}\n</blockquote>"

    def _render_list(self, node: MDList) -> str:
        """
        Render a list node to HTML.

        Args:
            node: The MDList node to render

        Returns:
            HTML string wrapped in <ol> or <ul> tags based on list type
        """
        tag = "ol" if node.list_type == ListType.ORDERED else "ul"

        # Add start attribute for ordered lists if not starting at 1
        start_attr = ""
        if node.list_type == ListType.ORDERED and node.start_number != 1:
            start_attr = f' start="{node.start_number}"'

        content: list[str] = []
        for child in node.children:
            content.append(self._render_node(child))

        inner_html = "\n".join(content)

        if node.is_tight:
            # Tight list - no <p> tags around single paragraph items
            inner_html = self._remove_paragraph_tags_from_list_items(inner_html)

        return f"<{tag}{start_attr}>\n{inner_html}\n</{tag}>"

    def _render_list_item(self, node: MDListItem) -> str:
        """
        Render a list item node to HTML.

        Args:
            node: The MDListItem node to render

        Returns:
            HTML string wrapped in <li> tags
        """
        content: list[str] = []
        for child in node.children:
            content.append(self._render_node(child))

        inner_html = "\n".join(content)
        return f"<li>{inner_html}</li>"

    def _render_horizontal_rule(self, node: MDHorizontalRule) -> str:
        """
        Render a horizontal rule node to HTML.

        Args:
            node: The MDHorizontalRule node to render

        Returns:
            HTML string with <hr> tag
        """
        return "<hr>"

    def _render_emphasis(self, node: MDEmphasis) -> str:
        """
        Render an emphasis node to HTML.

        Args:
            node: The MDEmphasis node to render

        Returns:
            HTML string with appropriate emphasis tags (<em>, <strong>, <del>, <u>, or <span>)
        """
        content = self._render_children(node)

        if node.emphasis_type == EmphasisType.ITALIC:
            return f"<em>{content}</em>"
        elif node.emphasis_type == EmphasisType.BOLD:
            return f"<strong>{content}</strong>"
        elif node.emphasis_type == EmphasisType.BOLD_ITALIC:
            return f"<strong><em>{content}</em></strong>"
        elif node.emphasis_type == EmphasisType.STRIKETHROUGH:
            return f"<del>{content}</del>"
        elif node.emphasis_type == EmphasisType.UNDERLINE:
            return f"<u>{content}</u>"
        elif node.emphasis_type == EmphasisType.SPOILER:
            return f'<span class="spoiler">{content}</span>'
        else:
            return content

    def _render_link(self, node: MDLink) -> str:
        """
        Render a link node to HTML.

        Args:
            node: The MDLink node to render

        Returns:
            HTML string with <a> tag containing href and optional title attributes
        """
        content = self._render_children(node)
        url = self._escape_html(node.url) if self.escape_html else node.url

        # Build attributes
        attrs = [f'href="{url}"']
        if node.title:
            title = self._escape_html(node.title) if self.escape_html else node.title
            attrs.append(f'title="{title}"')

        attr_string = " ".join(attrs)
        return f"<a {attr_string}>{content}</a>"

    def _render_image(self, node: MDImage) -> str:
        """
        Render an image node to HTML.

        Args:
            node: The MDImage node to render

        Returns:
            HTML string with <img> tag containing src, alt, and optional title attributes
        """
        url = self._escape_html(node.url) if self.escape_html else node.url
        alt_text = self._escape_html(node.alt_text) if self.escape_html else node.alt_text

        # Build attributes
        attrs = [f'src="{url}"', f'alt="{alt_text}"']
        if node.title:
            title = self._escape_html(node.title) if self.escape_html else node.title
            attrs.append(f'title="{title}"')

        attr_string = " ".join(attrs)
        return f"<img {attr_string}>"

    def _render_code_span(self, node: MDCodeSpan) -> str:
        """
        Render an inline code span node to HTML.

        Args:
            node: The MDCodeSpan node to render

        Returns:
            HTML string with <code> tag
        """
        content = self._escape_html(node.content) if self.escape_html else node.content
        return f"<code>{content}</code>"

    def _render_text(self, node: MDText) -> str:
        """
        Render a text node to HTML.

        Args:
            node: The MDText node to render

        Returns:
            Escaped or raw text content based on escape_html setting
        """
        content = node.content
        if self.escape_html:
            content = self._escape_html(content)
        return content

    def _render_autolink(self, node: MDAutolink) -> str:
        """
        Render an autolink node to HTML.

        Args:
            node: The MDAutolink node to render

        Returns:
            HTML string with <a> tag. Email autolinks get mailto: prefix added
        """
        url = node.url
        display_url = url

        # For email autolinks, add mailto: prefix
        if node.is_email and not url.startswith("mailto:"):
            url = f"mailto:{url}"

        if self.escape_html:
            url = self._escape_html(url)
            display_url = self._escape_html(display_url)

        return f'<a href="{url}">{display_url}</a>'

    def _render_children(self, node: MDNode) -> str:
        """
        Render all children of a node and return concatenated result.

        Args:
            node: The parent node whose children should be rendered

        Returns:
            Concatenated HTML string of all child nodes
        """
        content_parts: list[str] = []
        for child in node.children:
            content_parts.append(self._render_node(child))
        return "".join(content_parts)

    def _escape_html(self, text: str) -> str:
        """
        Escape HTML special characters in text.

        Args:
            text: The text to escape

        Returns:
            Text with HTML special characters (&, <, >, ", ') escaped
        """
        return html.escape(text, quote=True)

    def _remove_paragraph_tags_from_list_items(self, html_content: str) -> str:
        """
        Remove <p> tags from list items in tight lists.

        In tight lists, single paragraph items should not be wrapped in <p> tags.
        This method removes <p> tags from list items that contain only inline content.

        Args:
            html_content: The HTML content to process

        Returns:
            HTML content with <p> tags removed from tight list items

        Note:
            Only removes <p> tags from items that don't contain other block elements
            like div, blockquote, pre, ul, ol, li, or headers.
        """
        import re

        # Pattern to match <li><p>content</p></li> where content doesn't contain other block elements
        pattern = (
            r"<li><p>((?:(?!</?(?:p|div|blockquote|pre|ul|ol|li|h[1-6])\b)[^<]|"
            r"<(?!/?(?:p|div|blockquote|pre|ul|ol|li|h[1-6])\b)[^>]*>)*)</p></li>"
        )

        def replace_func(match):
            content = match.group(1)
            return f"<li>{content}</li>"

        return re.sub(pattern, replace_func, html_content, flags=re.IGNORECASE | re.DOTALL)

    def _indent(self) -> str:
        """
        Get current indentation string.

        Returns:
            String of spaces representing current indentation level
        """
        return " " * (self._indent_level * self.indent_size)

    def _increase_indent(self) -> None:
        """Increase the current indentation level by one."""
        self._indent_level += 1

    def _decrease_indent(self) -> None:
        """Decrease the current indentation level by one, if greater than zero."""
        if self._indent_level > 0:
            self._indent_level -= 1


class MarkdownRenderer:
    """
    Renderer that converts AST back to standard Markdown format.

    This renderer is useful for reformatting or normalizing Markdown documents.
    It converts the parsed AST back to clean, consistent Markdown output with
    configurable styling options.

    Attributes:
        options: Dictionary of rendering configuration options
        header_style: Style for headers - 'atx' (#) or 'setext' (===/---)
        emphasis_style: Style for emphasis - 'asterisk' (*) or 'underscore' (_)
        list_marker: Marker for unordered lists - '-', '*', or '+'

    Example:
        >>> renderer = MarkdownRenderer({"header_style": "atx", "list_marker": "-"})
        >>> markdown = renderer.render(document)
    """

    def __init__(self, options: Optional[Dict[str, Any]] = None) -> None:
        """
        Initialize the Markdown renderer with optional configuration.

        Args:
            options: Optional dictionary of rendering configuration options. Supported keys:
                - header_style (str): Style for headers - 'atx' (#) or 'setext' (===/---) (default: "atx")
                - emphasis_style (str): Style for emphasis - 'asterisk' (*) or 'underscore' (_) (default: "asterisk")
                - list_marker (str): Marker for unordered lists - '-', '*', or '+' (default: "-")
        """
        self.options: Dict[str, Any] = options or {}
        self.header_style: str = self.options.get("header_style", "atx")  # 'atx' or 'setext'
        self.emphasis_style: str = self.options.get("emphasis_style", "asterisk")  # 'asterisk' or 'underscore'
        self.list_marker: str = self.options.get("list_marker", "-")  # '-', '*', or '+'

    def render(self, document: MDDocument) -> str:
        """
        Render a Markdown document back to Markdown format.

        This is the main entry point for rendering. It validates the input document
        and renders all child nodes to Markdown with proper spacing.

        Args:
            document: The root MDDocument node to render

        Returns:
            Markdown string representation of the document

        Raises:
            ValueError: If the provided document is not an instance of MDDocument

        Example:
            >>> parser = MarkdownParser()
            >>> doc = parser.parse("# Hello\\nWorld")
            >>> renderer = MarkdownRenderer()
            >>> markdown = renderer.render(doc)
            >>> print(markdown)
            # Hello

            World
        """
        if not isinstance(document, MDDocument):
            raise ValueError("Expected MDDocument as root node")

        markdown_parts: list[str] = []
        for i, child in enumerate(document.children):
            if i > 0:
                markdown_parts.append("")  # Add blank line between blocks
            markdown_parts.append(self._render_node(child))

        return "\n".join(markdown_parts)

    def _render_node(self, node: MDNode) -> str:
        """
        Render a single AST node back to Markdown based on its type.

        This method dispatches to the appropriate rendering method based on the
        node's type. It handles all known node types.

        Args:
            node: The AST node to render

        Returns:
            Markdown string representation of the node

        Raises:
            ValueError: If the node type is unknown (should not occur with valid AST)
        """
        if isinstance(node, MDParagraph):
            return self._render_children(node)
        elif isinstance(node, MDHeader):
            content = self._render_children(node)
            return f"{'#' * node.level} {content}"
        elif isinstance(node, MDCodeBlock):
            if node.is_fenced:
                fence = "```"
                lang = node.language or ""
                return f"{fence}{lang}\n{node.content}\n{fence}"
            else:
                # Indent each line with 4 spaces
                lines = node.content.split("\n")
                indented_lines = ["    " + line for line in lines]
                return "\n".join(indented_lines)
        elif isinstance(node, MDBlockQuote):
            content = self._render_children(node)
            lines = content.split("\n")
            quoted_lines = ["> " + line for line in lines]
            return "\n".join(quoted_lines)
        elif isinstance(node, MDList):
            return self._render_list(node)
        elif isinstance(node, MDListItem):
            return self._render_list_item(node)
        elif isinstance(node, MDEmphasis):
            content = self._render_children(node)
            if node.emphasis_type == EmphasisType.ITALIC:
                return f"*{content}*"
            elif node.emphasis_type == EmphasisType.BOLD:
                return f"**{content}**"
            elif node.emphasis_type == EmphasisType.BOLD_ITALIC:
                return f"***{content}***"
            elif node.emphasis_type == EmphasisType.STRIKETHROUGH:
                return f"~~{content}~~"
            elif node.emphasis_type == EmphasisType.UNDERLINE:
                return f"++{content}++"
            elif node.emphasis_type == EmphasisType.SPOILER:
                return f"||{content}||"
        elif isinstance(node, MDLink):
            content = self._render_children(node)
            if node.title:
                return f'[{content}]({node.url} "{node.title}")'
            else:
                return f"[{content}]({node.url})"
        elif isinstance(node, MDImage):
            if node.title:
                return f'![{node.alt_text}]({node.url} "{node.title}")'
            else:
                return f"![{node.alt_text}]({node.url})"
        elif isinstance(node, MDCodeSpan):
            return f"`{node.content}`"
        elif isinstance(node, MDText):
            return node.content
        elif isinstance(node, MDAutolink):
            return f"<{node.url}>"
        elif isinstance(node, MDHorizontalRule):
            return "---"
        else:
            return self._render_children(node)

        # Actually it's unreachible, but linter whine about returning None
        raise ValueError(f"Unknown node type: {type(node)}")

    def _render_list(self, node: MDList) -> str:
        """
        Render a list node to Markdown.

        Args:
            node: The MDList node to render

        Returns:
            Markdown string with all list items joined by newlines
        """
        list_items: list[str] = []
        for child in node.children:
            if isinstance(child, MDListItem):
                list_items.append(self._render_list_item(child))
        return "\n".join(list_items)

    def _render_list_item(self, node: MDListItem) -> str:
        """
        Render a list item node to Markdown.

        Handles both simple list items and items with nested lists. Nested lists
        are properly indented with 3 spaces.

        Args:
            node: The MDListItem node to render

        Returns:
            Markdown string with list marker and content, including nested lists

        Note:
            For ordered lists, the marker is automatically numbered. For unordered
            lists, the configured list_marker is used.
        """
        # Separate text content from nested lists
        text_parts: list[str] = []
        nested_lists: list[MDList] = []

        for child in node.children:
            if isinstance(child, MDList):
                nested_lists.append(child)
            else:
                text_parts.append(self._render_node(child))

        # Render the main text content
        text_content = "".join(text_parts)

        # Determine list marker based on list type
        if hasattr(node, "parent") and isinstance(node.parent, MDList):
            if node.parent.list_type == ListType.ORDERED:
                # For ordered lists, we need the item number
                item_index = node.parent.children.index(node) + 1
                marker = f"{item_index}."
            else:
                # For unordered lists, use the configured marker
                marker = self.list_marker
        else:
            # Fallback to unordered marker
            marker = self.list_marker

        # Start with the main item
        result_lines: list[str] = [f"{marker} {text_content}"]

        # Add nested lists with proper indentation
        for nested_list in nested_lists:
            nested_content = self._render_list(nested_list)
            # Indent each line of the nested list
            nested_lines = nested_content.split("\n")
            for line in nested_lines:
                if line.strip():  # Don't indent empty lines
                    result_lines.append("   " + line)  # 3 spaces for nesting
                else:
                    result_lines.append(line)

        return "\n".join(result_lines)

    def _render_children(self, node: MDNode) -> str:
        """
        Render all children of a node and return concatenated result.

        Args:
            node: The parent node whose children should be rendered

        Returns:
            Concatenated Markdown string of all child nodes
        """
        content_parts: list[str] = []
        for child in node.children:
            content_parts.append(self._render_node(child))
        return "".join(content_parts)


class MarkdownV2Renderer:
    """
    Renderer that converts Markdown AST to Telegram's MarkdownV2 format.

    This renderer follows Telegram's MarkdownV2 specification with proper character
    escaping and format conversion. It handles the unique requirements of Telegram's
    markdown format, including special escaping rules and limited formatting support.

    Attributes:
        options: Dictionary of rendering configuration options
        preserve_leading_spaces: Whether to preserve leading spaces in paragraphs
        preserve_soft_line_breaks: Whether to preserve soft line breaks
        _escape: Function reference for escaping text based on context

    Example:
        >>> renderer = MarkdownV2Renderer({"preserve_leading_spaces": True})
        >>> markdown_v2 = renderer.render(document)
    """

    def __init__(self, options: Optional[Dict[str, Any]] = None) -> None:
        """
        Initialize the MarkdownV2 renderer with optional configuration.

        Args:
            options: Optional dictionary of rendering configuration options. Supported keys:
                - preserve_leading_spaces (bool): Whether to preserve leading spaces in paragraphs (default: False)
                - preserve_soft_line_breaks (bool): Whether to preserve soft line breaks (default: False)
        """
        self.options: Dict[str, Any] = options or {}

        # Renderer options
        self.preserve_leading_spaces: bool = self.options.get("preserve_leading_spaces", False)
        self.preserve_soft_line_breaks: bool = self.options.get("preserve_soft_line_breaks", False)

        self._escape = self._fallback_escape

    def render(self, document: MDDocument) -> str:
        """
        Render a Markdown document to MarkdownV2 format.

        This is the main entry point for rendering. It validates the input document
        and renders all child nodes to MarkdownV2 with proper spacing and escaping.

        Args:
            document: The root MDDocument node to render

        Returns:
            MarkdownV2 string representation of the document

        Raises:
            ValueError: If the provided document is not an instance of MDDocument

        Example:
            >>> parser = MarkdownParser()
            >>> doc = parser.parse("*bold* text")
            >>> renderer = MarkdownV2Renderer()
            >>> markdown_v2 = renderer.render(doc)
            >>> print(markdown_v2)
            *bold* text
        """
        if not isinstance(document, MDDocument):
            raise ValueError("Expected MDDocument as root node")

        parts: list[str] = []
        for i, child in enumerate(document.children):
            if i > 0:
                # Add blank line between block elements
                parts.append("")
            parts.append(self._render_node(child))

        return "\n".join(parts)

    def _render_node(self, node: MDNode) -> str:
        """
        Render a single AST node to MarkdownV2 based on its type.

        This method dispatches to the appropriate rendering method based on the
        node's type. It handles all known node types and provides a fallback for
        unknown types.

        Args:
            node: The AST node to render

        Returns:
            MarkdownV2 string representation of the node

        Note:
            Unknown node types are rendered as escaped text for debugging purposes.
        """
        if isinstance(node, MDDocument):
            return self._render_document(node)
        elif isinstance(node, MDParagraph):
            return self._render_paragraph(node)
        elif isinstance(node, MDHeader):
            return self._render_header(node)
        elif isinstance(node, MDCodeBlock):
            return self._render_code_block(node)
        elif isinstance(node, MDBlockQuote):
            return self._render_block_quote(node)
        elif isinstance(node, MDList):
            return self._render_list(node)
        elif isinstance(node, MDListItem):
            return self._render_list_item(node)
        elif isinstance(node, MDHorizontalRule):
            return self._render_horizontal_rule(node)
        elif isinstance(node, MDEmphasis):
            return self._render_emphasis(node)
        elif isinstance(node, MDLink):
            return self._render_link(node)
        elif isinstance(node, MDImage):
            return self._render_image(node)
        elif isinstance(node, MDCodeSpan):
            return self._render_code_span(node)
        elif isinstance(node, MDText):
            return self._render_text(node)
        elif isinstance(node, MDAutolink):
            return self._render_autolink(node)
        else:
            # Fallback for unknown node types
            return self._escape(f"[Unknown: {type(node).__name__}]", "general")

    def _render_document(self, node: MDDocument) -> str:
        """
        Render a document node by rendering all its children.

        Args:
            node: The MDDocument node to render

        Returns:
            Concatenated MarkdownV2 string of all child nodes with blank lines between blocks
        """
        parts: list[str] = []
        for i, child in enumerate(node.children):
            if i > 0:
                parts.append("")  # Blank line between blocks
            parts.append(self._render_node(child))
        return "\n".join(parts)

    def _render_paragraph(self, node: MDParagraph) -> str:
        """
        Render a paragraph node to MarkdownV2.

        Args:
            node: The MDParagraph node to render

        Returns:
            Rendered paragraph content, optionally preserving leading spaces
        """
        content = self._render_children(node)
        if self.preserve_leading_spaces:
            return content.rstrip()
        else:
            return content.strip()

    def _render_header(self, node: MDHeader) -> str:
        """
        Render a header node to MarkdownV2.

        Note: Headers are not directly supported in MarkdownV2, so they are rendered
        as escaped hash symbols followed by the content.

        Args:
            node: The MDHeader node to render

        Returns:
            Escaped hash symbols followed by the header content
        """
        content = self._render_children(node)
        # MarkdownV2 doesn't support headers so return as is
        return "\\#" * node.level + " " + content.strip()

    def _render_code_block(self, node: MDCodeBlock) -> str:
        """
        Render a code block node to MarkdownV2.

        Args:
            node: The MDCodeBlock node to render

        Returns:
            Code block wrapped in triple backticks with optional language specification
        """
        content = self._escape(node.content, "pre_code")

        if node.language:
            return f"```{node.language}\n{content}\n```"
        else:
            return f"```\n{content}\n```"

    def _render_block_quote(self, node: MDBlockQuote) -> str:
        """
        Render a block quote node to MarkdownV2.

        Args:
            node: The MDBlockQuote node to render

        Returns:
            Block quote with each line prefixed by >
        """
        parts: list[str] = []
        for child in node.children:
            child_content = self._render_node(child)
            lines = child_content.split("\n")
            for line in lines:
                if line.strip():
                    parts.append(f">{line}")
                else:
                    parts.append(">")
        return "\n".join(parts)

    def _render_list(self, node: MDList) -> str:
        """
        Render a list node to MarkdownV2.

        Note: Lists are not directly supported in MarkdownV2, so they are converted
        to simple text with bullet points or numbers.

        Args:
            node: The MDList node to render

        Returns:
            List items joined by newlines with appropriate markers
        """
        list_items: list[str] = []
        for child in node.children:
            if isinstance(child, MDListItem):
                list_items.append(self._render_list_item(child))
        return "\n".join(list_items)

    def _render_list_item(self, node: MDListItem) -> str:
        """
        Render a list item node to MarkdownV2.

        Handles both simple list items and items with nested lists. Nested lists
        are properly indented with 3 spaces.

        Args:
            node: The MDListItem node to render

        Returns:
            MarkdownV2 string with list marker and content, including nested lists

        Note:
            For ordered lists, the marker is automatically numbered. For unordered
            lists, a bullet point (•) is used.
        """
        # Separate text content from nested lists
        text_parts: list[str] = []
        nested_lists: list[MDList] = []

        for child in node.children:
            if isinstance(child, MDList):
                nested_lists.append(child)
            else:
                text_parts.append(self._render_node(child))

        # Render the main text content
        text_content = "".join(text_parts)

        # Determine list marker based on list type
        if hasattr(node, "parent") and isinstance(node.parent, MDList):
            if node.parent.list_type == ListType.ORDERED:
                # For ordered lists, we need the item number
                item_index = node.parent.children.index(node) + 1
                start_num = getattr(node.parent, "start_number", 1) + item_index - 1
                marker = f"{start_num}\\."
            else:
                # For unordered lists, use bullet
                marker = "•"
        else:
            # Fallback to unordered marker
            marker = "•"

        # Start with the main item
        result_lines: list[str] = [f"{marker} {text_content}"]

        # Add nested lists with proper indentation
        for nested_list in nested_lists:
            nested_content = self._render_list(nested_list)
            # Indent each line of the nested list
            nested_lines = nested_content.split("\n")
            for line in nested_lines:
                if line.strip():  # Don't indent empty lines
                    result_lines.append("   " + line)  # 3 spaces for nesting
                else:
                    result_lines.append(line)

        return "\n".join(result_lines)

    def _render_horizontal_rule(self, node: MDHorizontalRule) -> str:
        """
        Render a horizontal rule node to MarkdownV2.

        Note: Horizontal rules are not supported in MarkdownV2, so they are
        rendered as escaped dashes.

        Args:
            node: The MDHorizontalRule node to render

        Returns:
            Escaped dashes representing a horizontal rule
        """
        return self._escape("---", "general")

    def _render_emphasis(self, node: MDEmphasis) -> str:
        """
        Render an emphasis node to MarkdownV2.

        Args:
            node: The MDEmphasis node to render

        Returns:
            MarkdownV2 string with appropriate emphasis markers

        Note:
            MarkdownV2 uses different markers than standard Markdown:
            - Italic: _text_
            - Bold: *text*
            - Bold+Italic: *_text_*
            - Strikethrough: ~text~
            - Underline: __text__
            - Spoiler: ||text||
        """
        content = self._render_children(node)

        if node.emphasis_type == EmphasisType.ITALIC:
            return f"_{content}_"
        elif node.emphasis_type == EmphasisType.BOLD:
            return f"*{content}*"
        elif node.emphasis_type == EmphasisType.BOLD_ITALIC:
            return f"*_{content}_*"
        elif node.emphasis_type == EmphasisType.STRIKETHROUGH:
            return f"~{content}~"
        elif node.emphasis_type == EmphasisType.UNDERLINE:
            # Convert to _text_ for MarkdownV2 as requested
            return f"__{content}__"
        elif node.emphasis_type == EmphasisType.SPOILER:
            # Leave as-is for MarkdownV2 as requested
            return f"||{content}||"
        else:
            return content

    def _render_link(self, node: MDLink) -> str:
        """
        Render a link node to MarkdownV2.

        Args:
            node: The MDLink node to render

        Returns:
            MarkdownV2 link with properly escaped URL and content

        Note:
            Handles edge case where empty links might be false positives from
            emphasis marker parsing.
        """
        content = self._render_children(node)
        escaped_url = self._escape(node.url, "link_url")

        # If both content and URL are empty, this might be a false positive link
        # that consumed emphasis markers. In that case, reconstruct the likely original text.
        if not content.strip() and not node.url.strip():
            # This is likely a case where _*[]()~`! was parsed as an empty link
            # We need to escape these characters as they would appear in the original text
            return self._escape("_*[]()~`!", "general")

        return f"[{content}]({escaped_url})"

    def _render_image(self, node: MDImage) -> str:
        """
        Render an image node to MarkdownV2.

        Args:
            node: The MDImage node to render

        Returns:
            MarkdownV2 image or link representation

        Note:
            MarkdownV2 supports custom emoji via tg://emoji URLs. Regular images
            are converted to links since MarkdownV2 doesn't support standard images.
        """
        # MarkdownV2 supports custom emoji: ![👍](tg://emoji?id=5368324170671202286)
        # For regular images, we'll use a link format
        escaped_alt = self._escape(node.alt_text, "general")
        escaped_url = self._escape(node.url, "link_url")

        # Check if this looks like a Telegram emoji URL
        if "tg://emoji" in node.url:
            return f"![{escaped_alt}]({escaped_url})"
        else:
            # Regular image - convert to link since MarkdownV2 doesn't support images
            return f"[{escaped_alt}]({escaped_url})"

    def _render_code_span(self, node: MDCodeSpan) -> str:
        """
        Render an inline code span node to MarkdownV2.

        Args:
            node: The MDCodeSpan node to render

        Returns:
            Inline code wrapped in backticks with proper escaping
        """
        content = self._escape(node.content, "pre_code")
        return f"`{content}`"

    def _render_text(self, node: MDText) -> str:
        """
        Render a text node to MarkdownV2 with proper escaping.

        Args:
            node: The MDText node to render

        Returns:
            Text with all special characters properly escaped for MarkdownV2
        """
        return self._escape(node.content, "general")

    def _render_autolink(self, node: MDAutolink) -> str:
        """
        Render an autolink node to MarkdownV2.

        Args:
            node: The MDAutolink node to render

        Returns:
            MarkdownV2 link with properly escaped URL and display text

        Note:
            Email autolinks get mailto: prefix added automatically.
        """
        url = node.url
        display_url = node.url

        if node.is_email and not url.startswith("mailto:"):
            url = f"mailto:{url}"

        escaped_url = self._escape(url, "link_url")
        escaped_display = self._escape(display_url, "general")
        return f"[{escaped_display}]({escaped_url})"

    def _render_children(self, node: MDNode) -> str:
        """
        Render all children of a node and return concatenated result.

        Args:
            node: The parent node whose children should be rendered

        Returns:
            Concatenated MarkdownV2 string of all child nodes
        """
        parts: list[str] = []
        for child in node.children:
            parts.append(self._render_node(child))
        return "".join(parts)

    def _fallback_escape(self, text: str, context: str = "general") -> str:
        """
        Fallback escaping function for MarkdownV2 special characters.

        This function escapes special characters based on the context in which
        they appear. Different contexts require different characters to be escaped.

        Args:
            text: The text to escape
            context: The context for escaping. Valid values:
                - "pre_code": Escape backticks and backslashes (for code blocks/spans)
                - "link_url": Escape closing parentheses and backslashes (for URLs)
                - "general": Escape all MarkdownV2 special characters (default)

        Returns:
            Text with appropriate characters escaped with backslashes

        Note:
            Backslashes are always escaped first to avoid double-escaping issues.
        """
        if context == "pre_code":
            chars_to_escape = "`\\"
        elif context == "link_url":
            chars_to_escape = ")\\"
        else:  # general
            chars_to_escape = "_*[]()~`>#+-=|{}.!"

        # Escape backslashes first
        result = text.replace("\\", "\\\\")

        # Escape other special characters
        for char in chars_to_escape:
            if char != "\\":  # Already escaped backslashes
                result = result.replace(char, f"\\{char}")

        return result
