[stats]
enabled = false

llm-stats-data-source = "default"
stt-stats-data-source = "default"
message-stats-data-source = "default"
tool-stats-data-source = "default"
command-stats-data-source = "default"
