# Possible YC Models: https://aistudio.yandex.ru/docs/ru/ai-studio/concepts/generation/models.html
[models.models."yandex-art"]
provider = "yc-sdk"
model_id = "yandex-art"
model_version = "latest"
#temperature = 0.3
#context = 256000
support_tools = false
support_text = false
support_images = true
support_structured_output = false
tier = "paid"
