"""Webhook updates repository module.

This module provides the WebhookUpdatesRepository class for managing incoming
Max webhook payloads stored in the ``webhook_updates`` table. A thin webhook
receiver writes raw payloads here; a background consumer polls the unprocessed
rows, dispatches them to the bot, and marks them processed.

Key Classes:
    WebhookUpdatesRepository: Repository for webhook update storage and retrieval.

Note: This class deliberately does NOT subclass BaseRepository (which lives
in the bot's internal database layer). The repository is moved to lib/ for the
standalone webhook receiver, and BaseRepository is an internal-layer abstraction.
The manager-holding pattern is inlined directly: the class declares
__slots__ = ("manager",) and assigns it in __init__, byte-equivalent to the
BaseRepository contract.
"""

import datetime
import logging
from typing import List, Optional, Tuple

from dateutil import parser

from lib.db import utils as dbUtils
from lib.db.manager import DatabaseManager
from lib.db.providers import ParametrizedQuery
from lib.db.providers.base import QueryParams

from .models import WebhookUpdatesRow

logger = logging.getLogger(__name__)


class WebhookUpdatesRepository:
    """Repository for managing webhook update events in the database.

    Provides methods to store incoming webhook updates, retrieve unprocessed
    updates for the bot to consume, mark updates as processed, and clean up
    old processed events.

    Note: This class does NOT subclass BaseRepository (which lives
    in the bot's internal database layer). The manager-holding pattern is
    inlined directly so this repository can live in lib/ without internal-layer
    dependencies. The __slots__ and __init__ are byte-equivalent to BaseRepository.

    Attributes:
        manager: DatabaseManager instance that provides access to database
                providers and handles multi-source database operations.
    """

    __slots__ = ("manager",)
    """Restricts instance attributes to prevent dynamic attribute creation.

    Using __slots__ provides memory optimization by preventing the creation of
    a __dict__ for each instance, which is beneficial for repository classes
    that may be instantiated frequently. It also helps catch typos in attribute
    assignments at runtime.
    """

    def __init__(self, manager: DatabaseManager) -> None:
        """Initialize the webhook updates repository.

        Sets up the repository with access to the DatabaseManager, which
        provides the interface for all database operations.

        Args:
            manager: DatabaseManager instance for accessing database providers
                    and executing database operations. This manager should be
                    properly initialized with database connections before being
                    passed to the repository.

        Returns:
            None
        """
        self.manager = manager

    @staticmethod
    def _parseMarker(marker: str) -> Tuple[datetime.datetime, str]:
        """Split a compound marker into its timestamp and id components.

        A marker is the opaque string ``"{received_at}|{id}"`` returned by the
        GET /updates handler. The timestamp half is parsed back into a
        :class:`datetime.datetime` so that it can be handed to the provider
        as a real datetime (the provider serialises it via ``isoformat()``,
        matching how ``received_at`` is stored). Passing the raw string would
        compare SQLite's stored ISO form (``"T"`` separator) against
        ``str(datetime)`` (space separator) and silently mis-order rows.

        A marker without a ``|`` delimiter is treated as a bare timestamp
        with an empty id, so the id tie-breaker matches no row.

        Args:
            marker: Compound marker string ``"{received_at}|{id}"``.

        Returns:
            A ``(markerTs, markerId)`` tuple where ``markerTs`` is the parsed
            UTC datetime and ``markerId`` is the id substring (possibly empty).
        """
        markerParts = marker.split("|", 1)
        markerTs = parser.parse(markerParts[0])
        markerId = markerParts[1] if len(markerParts) > 1 else ""
        return markerTs, markerId

    async def addUpdate(self, updateId: str, updateType: str, rawJson: str, dataSource: Optional[str] = None) -> bool:
        """Store a raw webhook update in the database.

        Creates a new ``webhook_updates`` row in the pending (``processed = 0``)
        state. The caller is responsible for generating the ``updateId`` UUID
        before calling this method; the database never generates IDs.

        Args:
            updateId: Unique identifier (UUID) for this update, generated by
                    the caller before insert.
            updateType: The ``update_type`` string extracted from the Max API
                    payload, used for coarse routing.
            rawJson: Full webhook request body serialized as a JSON string.
            dataSource: Optional data source name to write to. If None, uses
                    the default data source configured in the DatabaseManager.

        Returns:
            bool: True if the update was stored successfully, False if an error
            occurred during insertion.
        """
        try:
            sqlProvider = await self.manager.getProvider(dataSource=dataSource, readonly=False)
            await sqlProvider.execute(
                """
                INSERT INTO webhook_updates
                    (id, received_at, update_type, raw_json, processed)
                VALUES
                    (:id, :receivedAt, :updateType, :rawJson, 0)
                """,
                {
                    "id": updateId,
                    "receivedAt": dbUtils.getCurrentTimestamp(),
                    "updateType": updateType,
                    "rawJson": rawJson,
                },
            )
            return True
        except Exception as e:
            logger.error(f"Failed to store webhook update: {e}")
            return False

    async def getUnprocessedUpdates(
        self,
        limit: int = 100,
        marker: Optional[str] = None,
        dataSource: Optional[str] = None,
    ) -> List[WebhookUpdatesRow]:
        """Retrieve unprocessed webhook updates ordered by arrival time.

        Rows are returned oldest-first so the consumer processes them in the
        order they were received. Pagination is applied through the provider so
        the LIMIT/OFFSET shape stays portable across SQLite/PostgreSQL/MySQL.

        When ``marker`` is provided, only rows strictly after that position are
        returned. This is used in deferred-acknowledgement mode: the caller
        passes back the marker from its previous poll, so already-delivered
        rows are excluded. The timestamp half of the marker is parsed back to a
        datetime and compared against ``received_at`` (with ``id`` as a
        tie-breaker for rows sharing the same arrival timestamp).

        Args:
            limit: Maximum number of updates to return.
            marker: Optional compound marker string (``"{received_at}|{id}"``).
                    When provided, only rows strictly newer than this position
                    are returned. When None, every unprocessed row is eligible.
            dataSource: Optional data source name to query. If None, uses the
                    default data source configured in the DatabaseManager.

        Returns:
            List[WebhookUpdatesRow]: Pending updates (``processed = 0``) in
            ascending ``received_at`` (then ``id``) order, filtered by the
            marker when given, or an empty list if none exist or an error
            occurs.
        """
        try:
            sqlProvider = await self.manager.getProvider(dataSource=dataSource, readonly=True)
            query = """
                SELECT id, received_at, update_type, raw_json, processed, processed_at
                FROM webhook_updates
                WHERE
            """
            params: QueryParams = {}
            if marker is not None:
                markerTs, markerId = self._parseMarker(marker)
                query += """
                    received_at > :markerTs
                    OR (received_at = :markerTs AND id > :markerId)
                """
                params["markerTs"] = markerTs
                params["markerId"] = markerId
            else:
                query += """
                    processed = 0
                """
            query += """
                ORDER BY received_at ASC, id ASC
            """
            query = sqlProvider.applyPagination(query, limit=limit, offset=0)
            result = await sqlProvider.executeFetchAll(query, params)
            return [dbUtils.sqlToTypedDict(row, WebhookUpdatesRow) for row in result] if result else []
        except Exception as e:
            logger.error("Failed to fetch unprocessed webhook updates: %s", e)
            return []

    async def markProcessed(self, updateIds: List[str], dataSource: Optional[str] = None) -> None:
        """Mark a batch of updates as processed atomically.

        All updates are written in a single ``batchExecute`` call so the entire
        batch succeeds or fails together. Per-row transactions would allow
        partial commits where some updates are marked processed and others are
        not, causing duplicate delivery on the next poll.

        Args:
            updateIds: List of update IDs to mark as processed.
            dataSource: Optional data source name to write to. If None, uses
                    the default data source configured in the DatabaseManager.

        Returns:
            None
        """
        if not updateIds:
            return

        try:
            sqlProvider = await self.manager.getProvider(dataSource=dataSource, readonly=False)
            now = dbUtils.getCurrentTimestamp()
            await sqlProvider.batchExecute(
                [
                    ParametrizedQuery(
                        """
                        UPDATE webhook_updates
                        SET processed = 1, processed_at = :processedAt
                        WHERE id = :id
                        """,
                        {"id": updateId, "processedAt": now},
                    )
                    for updateId in updateIds
                ]
            )
        except Exception as e:
            logger.error("Failed to mark webhook updates as processed: %s", e)

    async def markProcessedBeforeMarker(
        self,
        marker: str,
        dataSource: Optional[str] = None,
    ) -> None:
        """Mark all unprocessed updates at or before the given marker processed.

        Used in deferred-acknowledgement mode: when the bot passes the marker
        from its previous poll back, every unprocessed row whose position is at
        or before that marker is acknowledged as delivered. Rows strictly after
        the marker (or already-processed rows) are left untouched.

        Position is ``(received_at, id)``: a row qualifies when its
        ``received_at`` is strictly before the marker timestamp, or equal to it
        with ``id`` less-than-or-equal to the marker id. The timestamp is parsed
        to a datetime so the provider serialises it consistently with storage.

        Args:
            marker: Compound marker string (``"{received_at}|{id}"``) returned
                    by a previous GET /updates response. All unprocessed rows at
                    or before this position are marked processed.
            dataSource: Optional data source name to write to. If None, uses
                    the default data source configured in the DatabaseManager.

        Returns:
            None
        """
        markerTs, markerId = self._parseMarker(marker)
        try:
            sqlProvider = await self.manager.getProvider(dataSource=dataSource, readonly=False)
            now = dbUtils.getCurrentTimestamp()
            await sqlProvider.execute(
                """
                UPDATE webhook_updates
                SET processed = 1, processed_at = :now
                WHERE processed = 0
                  AND (received_at < :markerTs
                       OR (received_at = :markerTs AND id <= :markerId))
                """,
                {"now": now, "markerTs": markerTs, "markerId": markerId},
            )
        except Exception as e:
            logger.error("Failed to mark webhook updates before marker: %s", e)

    async def deleteProcessedOlderThan(self, ttlSeconds: int = 3600, dataSource: Optional[str] = None) -> bool:
        """Delete processed updates older than the specified TTL.

        Removes rows whose ``processed = 1`` and whose ``processed_at`` predates
        ``now - ttlSeconds``. The cutoff is computed in application code
        (mirroring ``cleanupOldCompletedDelayedTasks``) rather than relying on
        a DB-side time function, so the comparison is portable across providers.

        Args:
            ttlSeconds: Age threshold in seconds. Processed updates with
                    ``processed_at`` older than now - ttlSeconds are deleted.
            dataSource: Optional data source name to write to. If None, uses
                    the default data source configured in the DatabaseManager.

        Returns:
            bool: True if the deletion succeeded, False if an error occurred.
        """
        try:
            sqlProvider = await self.manager.getProvider(dataSource=dataSource, readonly=False)
            cutoff: datetime.datetime = dbUtils.getCurrentTimestamp() - datetime.timedelta(seconds=ttlSeconds)
            await sqlProvider.execute(
                """
                DELETE FROM webhook_updates
                WHERE processed = 1 AND processed_at < :cutoff
                """,
                {"cutoff": cutoff},
            )
            return True
        except Exception as e:
            logger.error("Failed to delete old processed webhook updates: %s", e)
            return False
